import fs from 'node:fs/promises';
import config from '../site.config.mjs';
const e = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for (const url of [config.origin, config.repository, config.release, config.license, ...Object.values(config.downloads)]) if(new URL(url).protocol !== 'https:') throw new Error('Public links must use HTTPS.');
const icon = (name) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({windows:'<path d="M3 4.5 10.5 3.5v7H3zM13 3l8-1v8.5h-8zM3 13h7.5v7L3 19zM13 13h8v9l-8-1z" fill="currentColor" stroke="none"/>',linux:'<path d="M8 9V6a4 4 0 0 1 8 0v3l3 7-2 4H7l-2-4z"/><path d="m9 11 3 2 3-2M8 20l-3 2M16 20l3 2"/><circle cx="10.5" cy="7" r=".6"/><circle cx="13.5" cy="7" r=".6"/>',cube:'<path d="m12 3 9 5-9 5-9-5 9-5zm-9 5v9l9 5 9-5V8m-9 5v9"/>',mods:'<path d="M9 3h6v4h4v6h-4v6H9v-4H3V9h6z"/>',account:'<circle cx="12" cy="7" r="4"/><path d="M4 21v-3a5 5 0 0 1 5-5h6a5 5 0 0 1 5 5v3"/>',tools:'<path d="m14 6 4 4M4 20l9-9M14 3l-3 3 7 7 3-3M3 17l4 4"/>',backup:'<path d="M3 5h6l2 3h10v13H3zM8 15l4-4 4 4m-4-4v7"/>',friends:'<circle cx="9" cy="7" r="3"/><path d="M2 21v-4a4 4 0 0 1 4-4h6a4 4 0 0 1 4 4v4M17 4a3 3 0 0 1 0 6m2 3a4 4 0 0 1 3 4v4"/>'})[name]}</svg>`;
const shots = [
 ['home','Home','Your launcher, at a glance.'],
 ['instances','Instances','A separate home for each Minecraft setup.'],
 ['mods','Mods','Find compatible content through Modrinth.'],
 ['modpacks','Modpacks','Browse complete Minecraft experiences.'],
 ['settings','Settings','Keep launcher preferences in one place.']
];
const screenshot = (id,label,priority=false) => `<button class="enlarge" data-enlarge="./screenshots/${id}.webp" data-caption="Novex Client — ${label}" aria-label="Enlarge ${label} screenshot"><img src="./screenshots/${id}.webp" alt="Actual Novex Client ${label} page, using a clean profile without personal account data" width="1440" height="968" ${priority?'fetchpriority="high"':'loading="lazy"'}><span class="zoom-hint">Enlarge screenshot ↗</span></button>`;
const header = page => `<a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap header-inner"><a class="brand" href="./index.html" aria-label="Novex home"><img src="./novex.png" width="34" height="34" alt="">Novex <span>Client</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu</button><nav id="main-nav" aria-label="Main navigation"><a href="./index.html" ${page==='index'?'aria-current="page"':''}>Home</a><a href="./index.html#features">Features</a><a href="./download.html" ${page==='download'?'aria-current="page"':''}>Download</a><a href="./index.html#screenshots">Screenshots</a><a href="./index.html#faq">FAQ</a><a class="nav-source" href="${e(config.repository)}">GitHub <span aria-hidden="true">↗</span></a></nav></div></header>`;
const footer = `<footer class="footer"><div class="wrap"><div class="footer-top"><a href="./index.html" class="brand"><img src="./novex.png" width="34" height="34" alt="">Novex <span>Client</span></a><div class="footer-links"><a href="./privacy.html">Privacy</a><a href="./terms.html">Terms</a><a href="./license.html">License</a><a href="${e(config.repository)}">GitHub ↗</a></div></div><div class="footer-bottom"><p>Novex Client is an independent third-party Minecraft launcher. Not affiliated with, endorsed by, or associated with Mojang Studios or Microsoft.</p><span>Novex Client · v${e(config.version)}</span></div></div></footer>`;
const lightbox = `<dialog id="image-dialog" class="lightbox" aria-labelledby="image-caption"><div class="lightbox-head"><p id="image-caption">Novex Client screenshot</p><button aria-label="Close screenshot">×</button></div><img alt=""></dialog>`;
const downloadCards = () => `<div class="download-grid"><article class="download-card"><div class="os-heading">${icon('windows')}<div><h3>Windows</h3><p class="os-meta">Windows 10 / 11 · x64</p></div><span class="tag">.exe</span></div><p>The familiar installer. Download Novex, choose where to install it, and make room for your next world.</p><a class="button" href="${e(config.downloads.windows)}">${icon('windows')}Download for Windows<span aria-hidden="true">↓</span></a><small>Novex Client ${e(config.version)} · NSIS installer</small><aside class="security-notice" aria-label="Windows security notice"><strong>Windows SmartScreen notice</strong><span>Novex’s current installer is unsigned, so SmartScreen may show an “unrecognized app” warning. This can reflect limited download reputation rather than detected malware. Download only from our linked GitHub release and verify the source before running it.</span><a href="https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/smartscreen-reputation">About SmartScreen ↗</a></aside></article><article class="download-card"><div class="os-heading">${icon('linux')}<div><h3 id="linux-packages">Linux</h3><p class="os-meta">x86_64 · AppImage / RPM / DEB</p></div><span class="tag">3 formats</span></div><p>Choose a portable AppImage or the package format for your Linux distribution.</p><p class="eyebrow">Choose your package</p><div class="linux-packages" aria-label="Linux download formats"><a href="${e(config.downloads.linux)}"><strong>AppImage <span aria-hidden="true">↓</span></strong><span>Portable · most distributions</span></a><a href="${e(config.downloads.linuxRpm)}"><strong>RPM <span aria-hidden="true">↓</span></strong><span>Fedora / compatible RPM systems</span></a><a href="${e(config.downloads.linuxDeb)}"><strong>DEB <span aria-hidden="true">↓</span></strong><span>Ubuntu / Linux Mint / Debian</span></a></div><small>Novex Client ${e(config.version)} · Fedora, Ubuntu, Mint & more</small></article></div><div class="download-foot"><span>Downloads are hosted on GitHub. A compatible Java installation is required to play.</span><a href="${e(config.release)}">Release notes & all available files ↗</a></div>`;
const features = [
 ['cube','A place for every setup','Import Modrinth packs and existing setups, then keep worlds and settings separate. Clone an instance, pin a favorite, and organize your library.'],
 ['mods','Mods, on your terms','Browse Modrinth mods and modpacks. Manage mods, resource packs and shaders. See clear enabled states, compatible updates and full Modrinth project pages inside Novex.'],
 ['account','Your Minecraft account','Sign in with Microsoft and select your Minecraft profile. Game ownership is verified. Your Novex social account stays separate.'],
 ['tools','Less launch guesswork','Detect installed Java, review performance health, and inspect crash hints. Missing platform libraries are repaired before launch.'],
 ['account','Your look, inside Novex','In the latest source: preview and apply Classic or Slim skins, keep local saved skins, and select capes owned by your Minecraft account.'],
 ['backup','Keep your worlds close','Browse local worlds and make manual backups. View screenshots, open instance files, and see approximate storage use.'],
 ['friends','A little more connected','Add friends and chat through your Novex account. Keep personal server favorites locally, ready to copy when you need them.']
];
const faq = [
 ['What is Novex Client?','An independent launcher for Minecraft Java Edition on Windows and Linux, with instance management and tools for finding and managing mods. It is not an official Minecraft product.'],
 ['Do I need to own Minecraft?','Yes, a legitimate Minecraft Java entitlement and profile are required for authenticated play. Novex checks ownership after Microsoft sign-in. An Offline / Local Account does not verify ownership or authenticate to online-mode servers.'],
 ['Which mod loaders are available?','The current launcher includes Vanilla, Fabric, Quilt, Forge and NeoForge installation paths. Availability depends on the selected Minecraft version. Choose mods that match both your version and loader.'],
 ['Where do mods and modpacks come from?','Modrinth is the default source. CurseForge is optional and requires separate operator configuration; the website does not promise it is available in every build. Downloads remain subject to their providers’ rules.'],
 ['Does Novex install Java for me?','The current source detects installed Java and supports managed runtimes based on Minecraft’s version requirements. You can also select your own compatible installation. Runtime availability depends on the launcher version.'],
 ['What happens to my instances and backups?','Instances and manual world backups stay on your computer. You can choose the instance storage directory. Automatic backups and restore controls are not included in this version.'],
 ['Where can I read the source and license?',`The source is available on <a href="${e(config.repository)}">GitHub</a>. Use is governed by the project’s <a href="${e(config.license)}">current LICENSE</a>. Third-party software retains its respective licenses.`]
];
const index = `<section class="hero wrap"><a class="release-chip" href="${e(config.release)}"><span class="dot"></span>VERSION ${e(config.version)}<span aria-hidden="true">/</span>WINDOWS + LINUX<span aria-hidden="true">↗</span></a><div class="hero-heading"><h1>Novex <span>Client.</span></h1><div><p class="lead">A modern Minecraft Java launcher.</p><p class="hero-description">Your worlds, your mods, your way to play. Bring every Minecraft setup together in one clean, focused launcher.</p><div class="actions"><a class="button" href="${e(config.downloads.windows)}">${icon('windows')}Download for Windows</a><a class="button secondary" href="./download.html#linux-packages">${icon('linux')}Download for Linux</a></div><a class="source-link" href="${e(config.repository)}">View Source <span aria-hidden="true">↗</span></a></div></div><figure class="hero-shot"><div class="frame-label"><span class="window-label"><img src="./novex.png" alt="">NOVEX CLIENT</span><span>YOUR NEXT SESSION STARTS HERE</span></div>${screenshot('home','Home',true)}</figure><div class="hero-caption"><span>Current development build · real screenshots · signed-out profile.</span><span>Built for Minecraft Java Edition</span></div><div class="loader-strip"><span class="eyebrow">Choose your setup</span><span>Vanilla</span><span>Fabric</span><span>Quilt</span><span>Forge</span><span>NeoForge</span></div></section>
<section class="section wrap" id="features"><div class="section-head"><div><span class="eyebrow">Made for your Minecraft</span><h2>Everything in its place.</h2></div><p>From a quiet vanilla world to a heavily modded adventure. Keep your setups separate and your next session close.</p></div><div class="feature-grid">${features.map(([i,title,body])=>`<article class="feature-card">${icon(i)}<h3>${title}</h3><p>${body}</p></article>`).join('')}</div><p class="feature-note">Features and screenshots reflect the current source, including improvements not yet in the v${e(config.version)} download. Social services require a configured Novex backend; loader and mod compatibility varies by version.</p></section>
<section class="section wrap" id="screenshots"><div class="section-head"><div><span class="eyebrow">Inside Novex</span><h2>A closer look.</h2></div><p>Actual screens from the launcher. No mockups, no account details. Select a page, then click to explore it.</p></div><div class="gallery-controls" aria-label="Choose a launcher screenshot" hidden>${shots.map(([id,label])=>`<button data-shot="${id}" aria-pressed="false">${label}</button>`).join('')}</div><div class="gallery">${shots.map(([id,label,description])=>`<figure>${screenshot(id,label)}<figcaption><strong>${label}</strong><span>${description}</span><span>Current development build</span></figcaption></figure>`).join('')}</div></section>
<section class="section wrap" id="download"><div class="section-head"><div><span class="eyebrow">Ready when you are</span><h2>Your next world awaits.</h2></div><p>Get Novex Client ${e(config.version)}.<br>Choose the download for your computer.</p></div>${downloadCards()}<p><a class="source-link" href="./download.html">Installation details <span aria-hidden="true">→</span></a></p></section>
<section class="section wrap" id="faq"><div class="faq-layout"><div class="section-head"><span class="eyebrow">Good to know</span><h2>A few answers<br>before you play.</h2><p>More questions or found a bug?<br><a class="subtle-link" href="${e(config.repository)}/issues">Visit the project on GitHub ↗</a></p></div><div class="faq-list">${faq.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></div></section>`;
const download = `<div class="wrap download-page"><header class="download-intro"><span class="eyebrow">Novex Client ${e(config.version)}</span><h1>Choose your platform.</h1><p>The same Novex experience on Windows and Linux. All downloads below are from the official Novex GitHub release.</p></header>${downloadCards()}<div class="install-help"><section><h2>Getting started on Windows</h2><ol><li>Download the x64 .exe installer.</li><li>Run it and follow the installation steps. The current build is unsigned; check that your download came from the linked Novex GitHub release.</li><li>Open Novex and sign in with your Microsoft account to use your Minecraft profile.</li><li>Choose a compatible Java installation and create an instance.</li></ol></section><section><h2>Getting started on Linux</h2><ol><li>Download the x86_64 AppImage.</li><li>In your file manager, open its properties and allow it to run as a program.</li><li>Open the AppImage. Some distributions require FUSE support to run AppImages.</li><li>Select an installed, compatible Java executable in Novex Settings.</li></ol></section></div><p class="feature-note">Normal launcher use does not require root. RPM and DEB files are only available when listed on the release page. Real game/loader compatibility still needs testing across individual setups.</p></div>`;
const legal = (title,body) => `<article class="wrap legal"><p class="eyebrow">Novex · Project information</p><h1>${title}</h1>${body}</article>`;
const privacy = legal('Privacy',`<p>This page describes this website. The desktop launcher has separate privacy information in its Legal section.</p><h2>A small, static website</h2><p>This site has no account system, forms, analytics scripts, advertising trackers, or website cookies. It does not read Minecraft files, launcher accounts, worlds, or screenshots from your device. The gallery images are public copies captured using a clean launcher profile.</p><h2>Hosting and downloads</h2><p>GitHub Pages hosts the site, and GitHub hosts the release downloads. GitHub may process IP addresses and request information to provide and protect its services. Read the <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub Privacy Statement</a> for details.</p><h2>Links to other services</h2><p>Following a download, source-code, or support link takes you to GitHub. Those services apply their own terms and privacy policies. Website images and styles are served locally; no external fonts or embedded tracking widgets are used.</p><h2>Questions</h2><p>You can contact the project through its <a href="${e(config.repository)}">GitHub repository</a>. Do not post passwords, authentication tokens, private logs, or personal information in public issues.</p>`);
const terms = legal('Terms',`<p>These terms describe use of the Novex website. Using the launcher also involves its in-app terms and the project’s LICENSE.</p><h2>Independent software</h2><p>Novex Client is an independent third-party Minecraft launcher. Novex is not affiliated with, endorsed by, or associated with Mojang Studios or Microsoft. Minecraft and associated names and marks belong to their respective owners.</p><h2>Downloads and use</h2><p>Downloads link to the Novex GitHub repository. Use of the software is governed by the <a href="${e(config.license)}">project’s current LICENSE</a>. Minecraft ownership, Microsoft accounts, mods, and other third-party services remain subject to their respective terms and licenses.</p><h2>Project information</h2><p>Features, platform availability, and system requirements can change between releases. Screenshots show the actual launcher using a clean profile; your content and configuration will differ. Back up important worlds and files before making changes to your setup.</p><h2>Availability</h2><p>This website and release information are provided as available. For the software’s warranty terms, refer to its LICENSE. Nothing on this page overrides rights that cannot be excluded under applicable law.</p>`);
const license = legal('License',`<p>Novex source code is available to read on GitHub. The project’s LICENSE is the authoritative statement of the permissions and conditions that apply to it.</p><h2>Novex Client</h2><p><a href="${e(config.license)}">Read the current Novex Client LICENSE ↗</a></p><p>Website descriptions do not replace or change that license. Consult the license included with the version you use.</p><h2>Third-party software</h2><p>Electron, React, Vite, Java runtimes, mod loaders, and other third-party software retain their respective licenses. Mods and modpacks have their own licenses and terms. Novex does not grant rights to Minecraft or third-party content.</p><h2>Logo and screenshots</h2><p>The Novex logo is reproduced from the launcher project without redesign. Gallery images show the actual Novex UI; third-party project icons and names may appear within the launcher’s content browser and remain the property of their respective owners.</p><p class="legal-note">Not an official Minecraft product. Not approved by or associated with Mojang Studios or Microsoft.</p>`);
const pages = {index:['Novex Client — A modern Minecraft Java launcher',index],download:['Download Novex Client for Windows & Linux',download],privacy:['Privacy — Novex Client',privacy],terms:['Terms — Novex Client',terms],license:['License — Novex Client',license]};
await fs.rm('dist',{recursive:true,force:true});
await fs.cp('public','dist',{recursive:true});
for(const [page,[title,body]] of Object.entries(pages)) {
 const description='Novex Client is an independent Minecraft Java launcher for Windows and Linux. Manage instances, browse mods and modpacks, and keep your setups organized.';
 const canonical=`${config.origin}/${page==='index'?'':page+'.html'}`;
 await fs.writeFile(`dist/${page}.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#08090a"><title>${e(title)}</title><meta name="description" content="${description}"><link rel="canonical" href="${e(canonical)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${description}"><meta property="og:type" content="website"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${e(config.origin)}/screenshots/home.webp"><link rel="icon" href="./favicon.ico"><link rel="stylesheet" href="./styles.css"><script src="./site.js" defer></script></head><body>${header(page)}<main id="main">${body}</main>${footer}${lightbox}</body></html>`);
}
console.log(`Built ${Object.keys(pages).length} pages for Novex ${config.version}.`);
